package com.erickafick.sportstracker;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.net.Uri;import android.provider.Settings;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity {
    LinearLayout root, content; ArrayList<JSONObject> players=new ArrayList<>(); EditText search; Spinner positionFilter; TextView stats; final String FILE="players.json";
    int green=Color.rgb(20,83,45), amber=Color.rgb(245,158,11), dark=Color.rgb(17,24,39);
    @Override public void onCreate(Bundle b){super.onCreate(b); load(); buildHome();}
    TextView tv(String s,int sp){ TextView t=new TextView(this); t.setText(s);t.setTextSize(sp);t.setTextColor(dark);t.setPadding(16,10,16,10);return t; }
    Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}
    void base(String title){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.WHITE);
      TextView bar=tv(title,20);bar.setTextColor(Color.WHITE);bar.setBackgroundColor(green);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(20,18,12,18);root.addView(bar,new LinearLayout.LayoutParams(-1,-2));
      ScrollView sv=new ScrollView(this); content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(10,8,10,20);sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root); }
    void buildHome(){base("ERICK SHINGIE AFICK SPORTS TRACKER");
      content.addView(tv("Offline Sports Team Player Management System",18));
      stats=tv("",15);content.addView(stats);refreshStats();
      Button add=btn("➕ Add Player");add.setOnClickListener(v->form(null));content.addView(add);
      Button list=btn("👥 Player Records");list.setOnClickListener(v->listPlayers());content.addView(list);
      Button analytics=btn("📊 Performance & Injury Analytics");analytics.setOnClickListener(v->analytics());content.addView(analytics);
      Button export=btn("📦 Export JSON / CSV");export.setOnClickListener(v->exportData());content.addView(export);
      Button about=btn("ℹ️ Objectives & System Information");about.setOnClickListener(v->about());content.addView(about);
    }
    void refreshStats(){int injured=0;for(JSONObject p:players)if(p.optBoolean("injured"))injured++;if(stats!=null)stats.setText("Players: "+players.size()+" / 500+ target    |    Injured: "+injured+"    |    Storage: OFFLINE");}
    void listPlayers(){base("PLAYER RECORDS");
      search=new EditText(this);search.setHint("Search name, ID, position...");content.addView(search);
      positionFilter=new Spinner(this);String[] ps={"All positions","Goalkeeper","Defender","Midfielder","Forward","Other"};positionFilter.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,ps));content.addView(positionFilter);
      LinearLayout row=new LinearLayout(this);Button go=btn("Search / Filter");Button add=btn("Add");row.addView(go,new LinearLayout.LayoutParams(0,-2,1));row.addView(add,new LinearLayout.LayoutParams(0,-2,1));content.addView(row);add.setOnClickListener(v->form(null));go.setOnClickListener(v->renderPlayers());renderPlayers(); }
    void renderPlayers(){for(int i=content.getChildCount()-1;i>=3;i--)content.removeViewAt(i);String q=search.getText().toString().toLowerCase();String pos=positionFilter.getSelectedItem().toString();
      int shown=0;for(JSONObject p:players){String hay=(p.optString("name")+" "+p.optString("id")+" "+p.optString("position")).toLowerCase();if(!hay.contains(q))continue;if(!pos.equals("All positions")&&!p.optString("position").equals(pos))continue; shown++;LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(8,8,8,8);card.setBackgroundColor(Color.rgb(245,247,250));
        TextView x=tv(p.optString("name")+"  •  #"+p.optString("id"),17);card.addView(x);card.addView(tv("Position: "+p.optString("position")+" | Age: "+p.optInt("age")+" | Fitness: "+p.optDouble("fitness",0),14));card.addView(tv("Efficiency: "+eff(p)+"% | Injury: "+(p.optBoolean("injured")?"Yes":"No"),14));
        LinearLayout r=new LinearLayout(this);Button edit=btn("Edit");Button del=btn("Delete");r.addView(edit,new LinearLayout.LayoutParams(0,-2,1));r.addView(del,new LinearLayout.LayoutParams(0,-2,1));card.addView(r);edit.setOnClickListener(v->form(p));del.setOnClickListener(v->delete(p));content.addView(card); }
      if(shown==0)content.addView(tv("No matching player records.",16)); }
    String eff(JSONObject p){double fitness=p.optDouble("fitness",0), perf=p.optDouble("performance",0), attendance=p.optDouble("attendance",0);return String.format(Locale.US,"%.1f",Math.min(100,fitness*.4+perf*.4+attendance*.2));}
    void form(JSONObject existing){base(existing==null?"ADD PLAYER":"EDIT PLAYER");EditText id=e("Player ID",existing);EditText name=e("Full Name",existing);EditText age=e("Age",existing);Spinner pos=new Spinner(this);String[] ps={"Goalkeeper","Defender","Midfielder","Forward","Other"};pos.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,ps));EditText fitness=e("Fitness Score (0-100)",existing);EditText performance=e("Performance Score (0-100)",existing);EditText attendance=e("Attendance (0-100)",existing);EditText contract=e("Contract Record",existing);EditText injuries=e("Injury History",existing);CheckBox inj=new CheckBox(this);inj.setText("Currently injured");if(existing!=null){for(int i=0;i<ps.length;i++)if(ps[i].equals(existing.optString("position")))pos.setSelection(i);inj.setChecked(existing.optBoolean("injured"));}
      content.addView(id);content.addView(name);content.addView(age);content.addView(tv("Position",14));content.addView(pos);content.addView(fitness);content.addView(performance);content.addView(attendance);content.addView(contract);content.addView(injuries);content.addView(inj);Button save=btn("Save Player");content.addView(save);save.setOnClickListener(v->{try{if(name.getText().toString().trim().isEmpty()||id.getText().toString().trim().isEmpty())throw new Exception("Player ID and name are required.");int a=Integer.parseInt(age.getText().toString());if(a<5||a>80)throw new Exception("Age must be between 5 and 80.");double f=Double.parseDouble(fitness.getText().toString()),pr=Double.parseDouble(performance.getText().toString()),at=Double.parseDouble(attendance.getText().toString());if(f<0||f>100||pr<0||pr>100||at<0||at>100)throw new Exception("Scores must be between 0 and 100.");JSONObject p=existing==null?new JSONObject():existing;p.put("id",id.getText().toString().trim());p.put("name",name.getText().toString().trim());p.put("age",a);p.put("position",pos.getSelectedItem().toString());p.put("fitness",f);p.put("performance",pr);p.put("attendance",at);p.put("contract",contract.getText().toString());p.put("injuries",injuries.getText().toString());p.put("injured",inj.isChecked());p.put("updated",new SimpleDateFormat("yyyy-MM-dd HH:mm",Locale.US).format(new Date()));if(existing==null)players.add(p);save();Toast.makeText(this,"Player saved",Toast.LENGTH_SHORT).show();buildHome();}catch(Exception ex){Toast.makeText(this,ex.getMessage(),Toast.LENGTH_LONG).show();}});}
    EditText e(String hint,JSONObject p){EditText e=new EditText(this);e.setHint(hint);e.setText(p==null?"":p.optString(hint.startsWith("Player ID")?"id":hint.startsWith("Full")?"name":hint.startsWith("Age")?"age":hint.startsWith("Fitness")?"fitness":hint.startsWith("Performance")?"performance":hint.startsWith("Attendance")?"attendance":hint.startsWith("Contract")?"contract":"injuries"));e.setInputType(hint.startsWith("Age")?2:hint.contains("Score")||hint.contains("Attendance")?2:1);return e;}
    void delete(JSONObject p){new AlertDialog.Builder(this).setTitle("Delete player?").setMessage(p.optString("name")).setNegativeButton("Cancel",null).setPositiveButton("Delete",(d,w)->{players.remove(p);save();listPlayers();}).show();}
    void analytics(){base("PERFORMANCE & INJURY ANALYTICS");if(players.isEmpty()){content.addView(tv("No records yet.",16));return;}double total=0;int inj=0;for(JSONObject p:players){total+=Double.parseDouble(eff(p));if(p.optBoolean("injured"))inj++;}content.addView(tv("Team average efficiency: "+String.format(Locale.US,"%.1f",total/players.size())+"%",20));content.addView(tv("Current injury cases: "+inj,17));for(JSONObject p:players){content.addView(tv(p.optString("name")+" — Efficiency "+eff(p)+"% — Injury: "+(p.optBoolean("injured")?"Yes":"No"),15));}}
    void about(){base("SYSTEM OBJECTIVES");content.addView(tv("Designed from the Sports Team Player Management System proposal.",16));content.addView(tv("• Secure local file-based storage for 500+ player profiles.\n• Fast local search and multi-criteria filtering by age, position and fitness.\n• Mathematical efficiency metrics and injury history summaries.\n• Input validation and recovery-oriented local storage.\n• Offline operation with JSON/CSV export.\n• CRUD: create, read, update and delete player records.",16));content.addView(tv("All core records remain on the device unless you explicitly export them.",15));}
    void load(){try{File f=new File(getFilesDir(),FILE);if(!f.exists())return;String s=new String(java.nio.file.Files.readAllBytes(f.toPath()));JSONArray a=new JSONArray(s);for(int i=0;i<a.length();i++)players.add(a.getJSONObject(i));}catch(Exception ignored){}}
    void save(){try{JSONArray a=new JSONArray();for(JSONObject p:players)a.put(p);FileOutputStream o=openFileOutput(FILE,MODE_PRIVATE);o.write(a.toString().getBytes());o.close();}catch(Exception e){Toast.makeText(this,"Storage error: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
    void exportData(){try{StringBuilder csv=new StringBuilder("id,name,age,position,fitness,performance,attendance,efficiency,injured,contract,injuries\n");for(JSONObject p:players){csv.append(q(p.optString("id"))).append(',').append(q(p.optString("name"))).append(',').append(p.optInt("age")).append(',').append(q(p.optString("position"))).append(',').append(p.optDouble("fitness")).append(',').append(p.optDouble("performance")).append(',').append(p.optDouble("attendance")).append(',').append(eff(p)).append(',').append(p.optBoolean("injured")).append(',').append(q(p.optString("contract"))).append(',').append(q(p.optString("injuries"))).append('\n');}File f=new File(getExternalFilesDir(null),"sports_players.csv");FileOutputStream o=new FileOutputStream(f);o.write(csv.toString().getBytes());o.close();Toast.makeText(this,"CSV exported to app storage: "+f.getAbsolutePath(),Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"Export failed: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
    String q(String s){return "\""+s.replace("\"","\"\"")+"\"";}
}
